{
 "title": "New dashboard",
 "time": { "from": "2026-07-29T05:56:20.519Z", "to": "2026-07-29T06:20:17.807Z" },
 "panels": [
  {
   "title": "Throughput per Phase (Prefill vs Decode)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(leaninfer_output_tokens_total[15s])",
     "legendFormat": "Decode"
    },
    {
     "expr": "rate(leaninfer_prompt_tokens_total[15s])",
     "legendFormat": "Prefill"
    }
   ]
  },
  {
   "title": "Step Cost by Phase (Prefill Stall Time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(leaninfer_step_duration_seconds_sum[30s]) / rate(leaninfer_step_duration_seconds_count[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prefill Time (not TTFT since Saturated Queue)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(leaninfer_prefill_seconds_sum[15s])\r\n/\r\nrate(leaninfer_prefill_seconds_count[15s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Per Output Token (TPOT)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "leaninfer_tpot_seconds_sum / leaninfer_tpot_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KV + Slot Util",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "leaninfer_kv_cache_tokens / leaninfer_kv_cache_capacity_tokens",
     "legendFormat": "KV Cache Util"
    },
    {
     "expr": "leaninfer_requests_running / leaninfer_slots_capacity",
     "legendFormat": "Cache Slot Util"
    }
   ]
  },
  {
   "title": "GPU UTIL / Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL", "legendFormat": "GPU Util" },
    { "expr": "DCGM_FI_DEV_POWER_USAGE", "legendFormat": "Power Draw" }
   ]
  },
  {
   "title": "Framebuffer Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "DCGM_FI_DEV_FB_USED", "legendFormat": "__auto" }
   ]
  }
 ]
}